# Generated by Django 5.0.6 on 2024-07-19 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 22, 51, 49, 215933, tzinfo=datetime.timezone.utc), verbose_name='Listing_endTime'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 22, 51, 49, 215933, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Listing_startTime'),
        ),
    ]
