# trunk-ignore-all(black)
# Generated by Django 5.0.6 on 2024-06-26 09:51

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_listing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Listing_startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 5, 51, 1, 607056)),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('list_item_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('add_to_list', models.CharField(choices=[('Add', 'Add')], max_length=3)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]