# Generated by Django 5.0.6 on 2024-08-09 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_listing_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_winner',
            field=models.CharField(blank=True, editable=False, max_length=90, null=True, verbose_name='Listing_winner'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 13, 58, 17, 207421, tzinfo=datetime.timezone.utc), verbose_name='Listing_endTime'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Listing_image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 13, 58, 17, 207421, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Listing_startTime'),
        ),
    ]
