# Generated by Django 5.0.6 on 2024-07-02 07:37

import datetime

from django.db import migrations, models

import auctions.validators


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_comments_comment_owner_id_listing_listing_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid_amount",
            field=models.IntegerField(validators=[auctions.validators.validate_bid]),
        ),
        migrations.AlterField(
            model_name="listing",
            name="Listing_endTime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 2, 3, 37, 54, 225910)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="Listing_startTime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 2, 3, 37, 54, 225910), editable=False
            ),
        ),
    ]
