# Generated by Django 5.0.6 on 2024-07-04 09:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0007_alter_bid_bid_amount_alter_listing_listing_endtime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid_amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="Listing_endTime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 5, 8, 8, 933242)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="Listing_image",
            field=models.ImageField(
                upload_to="../static/listings/images/f'{listing_id}'"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="Listing_startTime",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 5, 8, 8, 933242), editable=False
            ),
        ),
    ]
