# Generated by Django 5.0.6 on 2024-07-12 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bid_bid_amount_alter_listing_listing_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Listing_endTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 19, 4, 54, 842162)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Listing_image',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Listing_startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 19, 4, 54, 842162), editable=False),
        ),
    ]
