# trunk-ignore-all(checkov/CKV2_GHA_1)
name: Django CI

on:
  push:
    # trunk-ignore(yamllint/quoted-strings)
    branches: ["main"]
  pull_request:
    # trunk-ignore(yamllint/quoted-strings)
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.8, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
